location = /teresia-portal {
    return 302 $origin_proto://$http_host/teresia-portal/;
}

# API
location ~ ^/teresia-portal/api/(.*)$ {
    set $api_upstream http://api:9393/$1$is_args$args;
    proxy_pass $api_upstream;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    proxy_set_header Host               $http_host;
    proxy_set_header X-Forwarded-Host   $http_host;
    proxy_set_header X-Forwarded-Port   $server_port;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $origin_proto;
    proxy_set_header X-Forwarded-Ssl    $origin_ssl;
    proxy_set_header X-Forwarded-Scheme $origin_proto;
    proxy_connect_timeout 60s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;

    # CORS
    add_header Access-Control-Allow-Origin  *;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
    add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization";

    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin  *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization";
        add_header Access-Control-Max-Age  1728000;
        add_header Content-Type            'text/plain charset=UTF-8';
        add_header Content-Length          0;
        return 204;
    }
}

location ~ ^/teresia-portal/analytics(.*)$ {
    set $api_upstream http://api:9393/analytics$1$is_args$args;
    proxy_pass $api_upstream;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    proxy_set_header Host               $http_host;
    proxy_set_header X-Forwarded-Host   $http_host;
    proxy_set_header X-Forwarded-Port   $server_port;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $origin_proto;
    proxy_set_header X-Forwarded-Ssl    $origin_ssl;
    proxy_set_header X-Forwarded-Scheme $origin_proto;
    proxy_connect_timeout 60s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;
}

location ~ ^/teresia-portal/static(.*)$ {
    set $api_upstream http://api:9393/static$1$is_args$args;
    proxy_pass $api_upstream;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    proxy_set_header Host               $http_host;
    proxy_set_header X-Forwarded-Host   $http_host;
    proxy_set_header X-Forwarded-Port   $server_port;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $origin_proto;
    proxy_set_header X-Forwarded-Ssl    $origin_ssl;
    proxy_set_header X-Forwarded-Scheme $origin_proto;
    proxy_connect_timeout 60s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;
}

# Frontend Rails
location /teresia-portal/ {
    set $frontend_upstream http://frontend:3000;
    proxy_pass $frontend_upstream;
    proxy_set_header Host               $http_host;
    proxy_set_header X-Forwarded-Host   $http_host;
    proxy_set_header X-Forwarded-Port   $server_port;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $origin_proto;
    proxy_set_header X-Forwarded-Ssl    $origin_ssl;
    proxy_set_header SCRIPT_NAME        /teresia-portal;
    proxy_cookie_path / /teresia-portal/;

    proxy_connect_timeout  300s;
    proxy_send_timeout     300s;
    proxy_read_timeout     300s;
    proxy_request_buffering off;
}
